version: "3.1"

services:

  jenkins:
    image: vfarcic/jenkins
    ports:
      - 50000:50000
    networks:
      - proxy
    volumes:
      - jenkins:/var/jenkins_home
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.serviceDomain=jenkins.dockerflow.com
        - com.df.port=8080
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      resources:
        reservations:
          memory: 1000M
        limits:
          memory: 1500M
    secrets:
      - jenkins-user
      - jenkins-pass

  jenkins-agent:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://jenkins.dockerflow.com -labels "docker" -executors 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - jenkins-user
      - jenkins-pass

networks:
  proxy:
    external: true

volumes:
  jenkins:
    driver: cloudstor:aws

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true