version: "3.1"

services:

  jenkins-master:
    image: vfarcic/jenkins
    ports:
      - 50000:50000
    networks:
      - proxy
    volumes:
      - jenkins:/var/jenkins_home
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.serviceDomain=jenkins.dockerflow.com
        - com.df.port=8080
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      resources:
        reservations:
          memory: 1500M
        limits:
          memory: 2000M
    extra_hosts:
      - "${SLACK_HOST:-devops20.slack.com}:${SLACK_IP:-54.192.78.227}"
    secrets:
      - jenkins-user
      - jenkins-pass

  jenkins-agent:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://jenkins.dockerflow.com -labels "prod" -executors 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 150M
        limits:
          memory: 300M

networks:
  proxy:
    external: true

volumes:
  jenkins:
    driver: cloudstor:aws
    driver_opts:
      size: "25"
    external: false

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true