version: "3.1"

services:

  jenkins:
    image: vfarcic/jenkins
    ports:
      - 50000:50000
    networks:
      - proxy
    volumes:
      - jenkins:/var/jenkins_home
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.serviceDomain=jenkins.dockerflow.com
        - com.df.port=8080
    secrets:
      - jenkins-user
      - jenkins-pass

networks:
  proxy:
    external: true

volumes:
  jenkins:
    driver: cloudstor:aws

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true