version: "3.1"

services:

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 10M
        limits:
          memory: 20M

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - CONNECTION_MODE=http-keep-alive
    deploy:
      resources:
        reservations:
          memory: 10M
        limits:
          memory: 20M

  jenkins-master:
    image: vfarcic/jenkins
    ports:
      - 50000:50000
    networks:
      - proxy
    volumes:
      - jenkins:/var/jenkins_home
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.serviceDomain=jenkins.dockerflow.com
        - com.df.port=8080
      resources:
        reservations:
          memory: 1000M
        limits:
          memory: 1500M
    extra_hosts:
      - "${SLACK_HOST:-devops20.slack.com}:${SLACK_IP:-54.192.78.227}"
    secrets:
      - jenkins-user
      - jenkins-pass

  jenkins-agent:
    image: vfarcic/jenkins-swarm-agent:1.3
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://jenkins.dockerflow.com -labels "test" -executors 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 1000M
        limits:
          memory: 1500M
      replicas: 2

networks:
  proxy:
    external: true

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

volumes:
  jenkins:
    driver: cloudstor:aws
    driver_opts:
      size: "25"
    external: false
