version: "3.1"

services:

  jenkins-agent:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://jenkins.dockerflow.com -labels "prod" -executors 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 150M
        limits:
          memory: 300M

networks:
  proxy:
    external: true

volumes:
  jenkins:
    driver: cloudstor:aws
    driver_opts:
      size: "25"
    external: false

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true