version: "3.3"

services:

  jenkins-master:
    image: vfarcic/jenkins:${JENKINS_MASTER_TAG:-latest}
    ports:
      - 50000:50000
    networks:
      - proxy
      - default
    volumes:
      - jm:/var/jenkins_home
      - jmshare:/usr/share/jenkins/ref
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.serviceDomain=jenkins.dockerflow.com
        - com.df.port=8080
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
        - com.df.httpsOnly=true
      resources:
        reservations:
          memory: 2000M
        limits:
          memory: 2500M
    extra_hosts:
      - "${SLACK_HOST:-devops20.slack.com}:${SLACK_IP:-54.192.78.227}"
    secrets:
      - jenkins-user
      - jenkins-pass

  jenkins-agent:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://jenkins-master:8080 -labels "prod" -executors 2
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 500M
        limits:
          memory: 1000M

  nib0r-dfle-docs:
    image: nib0r/docker-flow-proxy-letsencrypt-docs:${NIB0R_DFLE_DOCS_TAG:-latest}
    networks:
      - proxy
    deploy:
      labels:
        - com.df.distribute=true
        - com.df.notify=true
        - com.df.port=80
        - com.df.serviceDomain=nib0r-letsencrypt.dockerflow.com
        - com.df.servicePath=/
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      replicas: 2
      resources:
        reservations:
          memory: 5M
        limits:
          memory: 10M

  docs:
    image: vfarcic/docker-flow-hub-docs:${TAG:-latest}
    networks:
      - proxy
    deploy:
      labels:
        - com.df.distribute=true
        - com.df.notify=true
        - com.df.port=80
        - com.df.serviceDomain=www.dockerflow.com,dockerflow.com
        - com.df.servicePath=/
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      replicas: 2
      resources:
        reservations:
          memory: 5M
        limits:
          memory: 10M

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    environment:
      - xpack.security.enabled=false
#    volumes:
#      - es:/usr/share/elasticsearch/data
    networks:
      - default
    deploy:
      labels:
        - com.df.distribute=true
        - com.df.notify=true
        - com.df.port=80
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      resources:
        reservations:
          memory: 3000M
        limits:
          memory: 3500M
      placement:
        constraints: [node.role == worker]

  logstash:
    image: vfarcic/logstash:5.5.2
    networks:
      - default
    deploy:
      labels:
        - com.df.distribute=true
        - com.df.notify=true
        - com.df.port=80
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      resources:
        reservations:
          memory: 600M
        limits:
          memory: 1000M
    environment:
      - LOGSPOUT=ignore

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    networks:
      - default
      - proxy
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.usersPassEncrypted=false
        - com.df.usersSecret=vfarcic
        - com.df.serviceDomain=kibana.dockerflow.com
        - com.df.port=5601
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      resources:
        reservations:
          memory: 500M
        limits:
          memory: 1000M

  logspout:
    image: gliderlabs/logspout:v3.2.2
    networks:
      - default
    environment:
      - SYSLOG_FORMAT=rfc3164
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: syslog://logstash:51415
    deploy:
      mode: global
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      resources:
        reservations:
          memory: 20M
        limits:
          memory: 30M

networks:
  proxy:
    external: true
  default:
    external: false

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

volumes:
  jm:
    driver: cloudstor:aws
    external: false
  jmshare:
    driver: cloudstor:aws
    external: false
